export const languageOptions=[
  {code:'ko',label:'한국어',locale:'ko-KR'},
  {code:'en',label:'English',locale:'en-US'},
  {code:'zh',label:'简体中文',locale:'zh-CN'},
  {code:'vi',label:'Tiếng Việt',locale:'vi-VN'},
  {code:'mn',label:'Монгол',locale:'mn-MN'},
  {code:'ja',label:'日本語',locale:'ja-JP'},
]
export const supportedLanguages=languageOptions.map(item=>item.code)

const ko={
 meta:{title:'옥토퍼스 토픽 | 매일 한 걸음 TOPIK',description:'오늘의 퀴즈와 TOPIK II 53번 그래프 쓰기를 매일 연습하고 학습 포인트를 쌓아 보세요.'},
 layout:{home:'옥토퍼스 토픽 홈',nav:'주요 메뉴',dashboard:'대시보드',quiz:'오늘의 퀴즈',answers:'쓰기 연습',login:'로그인',start:'무료로 시작하기',logout:'로그아웃',language:'언어 선택',menu:'메뉴 열기',footer:'오늘의 한 문제가 합격에 가까워지게 합니다.'},
 landing:{eyebrow:'TOPIK 학습, 오늘부터 가볍게',before:'매일 한 문제,',strong:'합격에 가까워지는',after:'습관',description:'오늘의 퀴즈부터 TOPIK II 53번 그래프 쓰기까지.\n나만의 학습 기록을 차곡차곡 쌓아 보세요.',continue:'학습 계속하기',start:'무료로 시작하기',free:'가입 즉시 무료 · 카드 등록 없음',visual:'옥토와 함께하는 TOPIK 성장 흐름',visualAlt:'오늘의 미션을 완료하고 포인트를 모으는 옥토 캐릭터',mission:'오늘의 미션 +50 P',goal:'오늘의 목표',goalText:'읽기 퀴즈 3문제',trust:'혼자여도 막막하지 않게',trustItems:['오늘의 퀴즈','즉시 해설','쓰기 기록','포인트 보상'],kicker:'작지만 확실한 학습 루틴',title:'TOPIK 준비에 필요한 것만 담았어요',intro:'복잡한 계획 대신, 매일 완료할 수 있는 분량으로 시작하세요.',features:[['3분 오늘의 퀴즈','실전 유형 문제를 풀고 정답과 해설을 바로 확인해요.'],['53번 그래프 쓰기','그래프의 핵심 수치를 비교하며 200~300자 답안을 연습해요.'],['눈에 보이는 성장','학습을 마칠 때마다 포인트와 기록이 차곡차곡 쌓여요.']],ctaKicker:'오늘이 가장 빠른 시작이에요',ctaTitle:'첫 문제를 풀 준비가 됐나요?',cta:'지금 시작하기'},
 login:{secure:'내 기기에 안전하게 저장',headline:'옥토와 다시\n성장해 볼까요?',subtitle:'로그인하고 오늘의 작은 미션을 이어가세요.',alt:'학습 습관을 응원하는 옥토 캐릭터',quote:'“하루에 한 문제씩 풀었더니\n어느새 읽기 문제가 익숙해졌어요.”',quoteBy:'— TOPIK 학습자 수민',home:'홈으로',title:'로그인',intro:'아직 계정이 없나요? 아무 이메일로 바로 시작할 수 있어요.',email:'이메일',password:'비밀번호',passwordPlaceholder:'4자 이상 입력',toggle:'비밀번호 표시 전환',submit:'로그인하고 학습하기',demo:'체험 안내',demoText:'입력한 정보는 이 브라우저에만 저장됩니다.',emailError:'올바른 이메일 주소를 입력해 주세요.',passwordError:'비밀번호를 4자 이상 입력해 주세요.'},
 common:{loading:'학습 기록을 불러오고 있어요',back:'돌아가기',home:'홈으로 돌아가기',empty:'아직 기록이 없어요',save:'저장하기',writing:'TOPIK II · 쓰기',reading:'TOPIK II · 읽기',characters:'자',items:'개',days:'일'},
 dashboard:{greeting:'님, 오늘도',step:'한 걸음',question:'가볼까요?',subtitle:'작은 학습이 쌓여 큰 실력이 됩니다.',record:'학습 기록',points:'보유 포인트',pointsNote:'학습할수록 쌓여요',completed:'완료한 학습',completedNote:'오늘도 기록해 보세요',written:'작성한 쓰기 답안',view:'답안 모아보기',today:'오늘의 학습',daily:'1일 권장 학습량',quizTitle:'오늘의 퀴즈 3문제',quizDesc:'실전 감각을 깨우는 짧고 알찬 문제예요.',threeMin:'약 3분',quizReward:'완료 시 최대 +50 P',retry:'다시 풀기',quizStart:'퀴즈 시작',writeTitle:'53·54번 쓰기 연습',writeDesc:'그래프 설명과 논술 중 오늘 연습할 문제를 선택하세요.',fifteenMin:'약 15~40분',writeReward:'완료 시 최대 +50 P',write:'쓰기 선택',weekly:'이번 주 학습',questions:'27문제',weeklyGoal:'주간 목표',tip:'오늘의 학습 팁',tipText:'문제를 틀렸다면 정답보다 왜 틀렸는지 한 문장으로 정리해 보세요.'},
 quiz:{exit:'나가기',previous:'이전 문제',title:'오늘의 퀴즈',time:'약 3분',choose:'정답 선택',selectError:'답을 하나 선택해 주세요.',hint:'하나의 답을 선택하세요',next:'다음 문제',result:'결과 확인하기'},
 result:{emptyTitle:'아직 완료한 퀴즈가 없어요',emptyText:'오늘의 퀴즈를 먼저 풀어 주세요.',start:'퀴즈 시작하기',complete:'오늘의 퀴즈 완료',great:'정말 잘했어요!',good:'좋은 시작이에요!',correctSuffix:'문제를 맞혔어요. 해설을 확인하면 실력이 더 단단해져요.',already:'이미 적립된 퀴즈예요',earned:'학습 완료 포인트 적립!',correct:'정답',rate:'정답률',points:'학습 포인트',review:'문제 다시 보기',answers:'정답과 해설',retry:'다시 풀기',wrong:'오답',my:'내 답',noRecord:'기록 없음',explanation:'해설',dashboard:'대시보드',write:'53번 답안 쓰기',score:'점'},
 writingHome:{title:'53번과 54번, 오늘의 쓰기를 선택하세요',intro:'문제 풀이와 기본 해설은 계속 무료예요. 답안을 저장하고 나만의 쓰기 기록을 쌓아 보세요.',history:'내 답안 기록',q53Title:'그래프 자료 설명',q53Text:'핵심 수치와 증감 폭을 비교해 객관적으로 설명하는 연습이에요.',q53Meta:'200~300자 · 약 15분',q54Title:'주제 논술',q54Text:'세 가지 과제를 빠짐없이 다루며 자신의 생각을 논리적으로 전개해요.',q54Meta:'600~700자 · 약 40분',start:'오늘 문제 풀기'},
 writing:{title:'번 그래프 답안 작성',title54:'번 논술 답안 작성',subtitle:'자료의 핵심 수치와 변화를 객관적으로 설명해 보세요.',subtitle54:'주어진 과제를 모두 다루며 생각을 논리적으로 전개해 보세요.',backToLab:'쓰기 연습으로',saved:'임시 저장됨',autosave:'자동 저장',graph:'그래프 문제',essay:'논술 문제',tip:'53번 쓰기 팁',tipText:'의견은 넣지 말고 수치를 비교해 객관적으로 서술하세요.',tip54:'54번 쓰기 팁',tipText54:'세 가지 과제를 모두 다루고 도입·본론·결론의 역할을 분명히 하세요.',my:'나의 답안',recommended:'권장 200~300자',recommended54:'권장 600~700자',content:'답안 내용',placeholder:'조사 결과에 따르면 온라인 쇼핑 이용률은 모든 연령대에서...',placeholder54:'현대 사회에서는 새로운 기술과 생활 방식의 변화로 인해...',autoNote:'작성 중인 내용은 자동 저장돼요.',save:'답안 저장하기',saveComplete:'저장 완료',lengthError:'답안을 200~300자로 작성해 주세요.',lengthError54:'답안을 600~700자로 작성해 주세요.',feedbackKickerText:'학습 완료',feedbackTitle:'정답 해설을 확인해 보세요',feedbackIntro:'내 답안과 예시 답안을 비교하며 핵심 수치가 빠짐없이 들어갔는지 확인하세요.',feedbackTitle54:'무료 구성 가이드를 확인해 보세요',feedbackIntro54:'공식 평가 영역을 기준으로 과제와 글의 구조를 점검해 보세요.',mySavedAnswer:'저장한 나의 답안',modelAnswer:'예시 답안',outline:'답안 구성 예시',explanation:'핵심 해설',viewAnswers:'답안 보관함 보기'},
 premium:{badge:'PREMIUM 첨삭',title:'내 답안에 꼭 맞는 첨삭이 필요하다면',intro:'무료 문제와 기본 해설은 그대로 유지하고, 개인 문장 교정과 연습 점수는 프리미엄으로 제공할 예정입니다.',featureScore:'평가 영역별 AI 연습 점수',featureCorrection:'문장별 교정과 수정 이유',featureRewrite:'내 답안을 반영한 개선 답안',resultTitle:'이 답안의 맞춤 첨삭을 받아 보세요',resultText:'누락된 내용, 어색한 문장, 예상 감점 요소를 내 답안을 기준으로 분석합니다.',soon:'베타 준비 중'},
 answers:{title:'쓰기 답안 보관함',intro:'작성한 53번과 54번 답안을 다시 읽으며 나의 변화를 확인하세요.',new:'새 답안 쓰기',emptyTitle:'아직 작성한 답안이 없어요',emptyText:'53번 또는 54번 첫 답안을 작성하면 이곳에 안전하게 보관해 드릴게요.',first:'첫 답안 작성하기',graph:'TOPIK II 53번 그래프',essay:'TOPIK II 54번 논술',list:'답안 목록',notFound:'답안을 찾을 수 없어요',notFoundText:'삭제되었거나 올바른 쓰기 기록이 아닙니다.',my:'나의 쓰기 답안',back:'목록으로 돌아가기',sameType:'같은 유형 다시 쓰기'},
 notFound:{title:'길을 잃은 것 같아요',text:'요청하신 페이지가 없거나 주소가 변경되었습니다.'}
}

const en={
 meta:{title:'Octopus TOPIK | One Step Every Day',description:'Practice daily TOPIK quizzes and Question 53 graph writing while building a visible learning record.'},
 layout:{home:'Octopus TOPIK home',nav:'Main menu',dashboard:'Dashboard',quiz:"Today's quiz",answers:'Writing practice',login:'Log in',start:'Start for free',logout:'Log out',language:'Choose language',menu:'Open menu',footer:"Today's small step brings you closer to your TOPIK goal."},
 landing:{eyebrow:'Start TOPIK lightly today',before:'One question a day,',strong:'one step closer',after:'to your goal',description:"From today's quiz to TOPIK II Question 53 graph writing.\nBuild your own learning record, one small win at a time.",continue:'Continue learning',start:'Start for free',free:'Free to join · No card required',visual:'Your TOPIK growth journey with Octo',visualAlt:'Octo completes a daily mission and earns points',mission:"Today's mission +50 P",goal:"Today's goal",goalText:'3 reading questions',trust:'Never feel stuck studying alone',trustItems:["Today's quiz",'Instant explanations','Writing records','Point rewards'],kicker:'A small routine that works',title:'Only what you need for TOPIK',intro:'Skip the complicated plan and start with a daily goal you can finish.',features:[["3-minute daily quiz",'Solve exam-style questions and check answers and explanations right away.'],['Question 53 graph writing','Compare key figures and practice a 200–300 character answer.'],['Visible progress','Points and records build up every time you finish a lesson.']],ctaKicker:'The best time to start is today',ctaTitle:'Ready to solve your first question?',cta:'Start now'},
 login:{secure:'Saved safely on your device',headline:'Ready to grow\nwith Octo again?',subtitle:"Log in and continue today's small mission.",alt:'Octo cheering on your study habit',quote:'“One question a day made\nreading feel familiar.”',quoteBy:'— Sumin, TOPIK learner',home:'Back home',title:'Log in',intro:'No account yet? Start with any email address.',email:'Email',password:'Password',passwordPlaceholder:'At least 4 characters',toggle:'Show or hide password',submit:'Log in and learn',demo:'Demo notice',demoText:'Your information is stored only in this browser.',emailError:'Enter a valid email address.',passwordError:'Use at least 4 characters.'},
 common:{loading:'Loading your learning record',back:'Go back',home:'Back home',empty:'No records yet',save:'Save',writing:'TOPIK II · Writing',reading:'TOPIK II · Reading',characters:' chars',items:'',days:' days'},
 dashboard:{greeting:', ready for',step:'one more step',question:'today?',subtitle:'Small lessons grow into real skill.',record:'Study streak',points:'Points',pointsNote:'Earn more as you learn',completed:'Completed lessons',completedNote:'Add another record today',written:'Writing answers',view:'View all answers',today:"Today's learning",daily:'Recommended daily amount',quizTitle:"Today's 3-question quiz",quizDesc:'A short set that wakes up your exam instincts.',threeMin:'About 3 min',quizReward:'Up to +50 P',retry:'Try again',quizStart:'Start quiz',writeTitle:'Practice Questions 53 & 54',writeDesc:'Choose graph description or long-form essay practice.',fifteenMin:'About 15–40 min',writeReward:'Up to +50 P',write:'Choose writing',weekly:'This week',questions:'27 questions',weeklyGoal:'Weekly goal',tip:"Today's study tip",tipText:'When you miss a question, write one sentence explaining why—not just the correct answer.'},
 quiz:{exit:'Exit',previous:'Previous',title:"Today's quiz",time:'About 3 min',choose:'Choose an answer',selectError:'Choose one answer.',hint:'Select one answer',next:'Next question',result:'See results'},
 result:{emptyTitle:'No completed quiz yet',emptyText:"Complete today's quiz first.",start:'Start quiz',complete:"Today's quiz complete",great:'Excellent work!',good:'A great start!',correctSuffix:' correct. Review the explanations to make your skills stronger.',already:'Points already awarded',earned:'Completion points added!',correct:'Correct',rate:'Accuracy',points:'Learning points',review:'Review questions',answers:'Answers and explanations',retry:'Try again',wrong:'Incorrect',my:'My answer',noRecord:'No record',explanation:'Explanation',dashboard:'Dashboard',write:'Write a Q53 answer',score:'pts'},
 writingHome:{title:'Choose Question 53 or 54 for today',intro:'Prompts and basic guidance stay free. Save each answer and build your writing history.',history:'My writing history',q53Title:'Describe graph data',q53Text:'Compare key figures and changes objectively.',q53Meta:'200–300 chars · about 15 min',q54Title:'Long-form essay',q54Text:'Address all three tasks and develop your ideas logically.',q54Meta:'600–700 chars · about 40 min',start:"Start today's prompt"},
 writing:{title:'Graph answer writing',title54:'Long-form essay writing',subtitle:'Describe the key figures and changes objectively.',subtitle54:'Address every task and develop your ideas logically.',backToLab:'Back to writing lab',saved:'Draft saved',autosave:'Auto save',graph:'Graph task',essay:'Essay task',tip:'Question 53 tip',tipText:'Avoid opinions. Compare the figures and describe them objectively.',tip54:'Question 54 tip',tipText54:'Address all three tasks and make the roles of the introduction, body, and conclusion clear.',my:'My answer',recommended:'Recommended: 200–300 Korean characters',recommended54:'Recommended: 600–700 Korean characters',content:'Answer',placeholder:'According to the survey, online shopping use increased in every age group...',placeholder54:'In modern society, new technology and changing lifestyles have...',autoNote:'Your draft is saved automatically.',save:'Save answer',saveComplete:'Saved',lengthError:'Write between 200 and 300 Korean characters.',lengthError54:'Write between 600 and 700 Korean characters.',feedbackKickerText:'Study complete',feedbackTitle:'Review the model answer',feedbackIntro:'Compare your response with the model and check whether you included the key figures.',feedbackTitle54:'Review the free structure guide',feedbackIntro54:'Check your task completion and organization against the official assessment areas.',mySavedAnswer:'My saved answer',modelAnswer:'Model answer',outline:'Suggested answer structure',explanation:'Key explanation',viewAnswers:'View answer library'},
 premium:{badge:'PREMIUM feedback',title:'Want feedback tailored to your answer?',intro:'Prompts and basic guidance remain free. Personal corrections and practice scores will be offered as Premium feedback.',featureScore:'Practice score by assessment area',featureCorrection:'Sentence-level corrections with reasons',featureRewrite:'Improved answer based on your draft',resultTitle:'Get tailored feedback on this answer',resultText:'Analyze missing content, awkward sentences, and potential point deductions in your own response.',soon:'Beta coming soon'},
 answers:{title:'Writing answer library',intro:'Review your Question 53 and 54 answers and track your progress.',new:'Write a new answer',emptyTitle:'No answers yet',emptyText:'Your first Question 53 or 54 answer will be saved here.',first:'Write your first answer',graph:'TOPIK II Question 53 graph',essay:'TOPIK II Question 54 essay',list:'Answer list',notFound:'Answer not found',notFoundText:'This record may be missing or may not be a valid writing answer.',my:'My writing answer',back:'Back to list',sameType:'Practice this type again'},
 notFound:{title:'Looks like you are lost',text:'The page does not exist or its address has changed.'}
}

const zh={...en,meta:{title:'Octopus TOPIK | 每天前进一步',description:'每天练习TOPIK测验和53题图表写作，积累积分和学习记录。'},layout:{home:'Octopus TOPIK首页',nav:'主菜单',dashboard:'学习面板',quiz:'今日测验',answers:'53题答案',login:'登录',start:'免费开始',logout:'退出登录',language:'选择语言',menu:'打开菜单',footer:'今天的一小步，让你更接近TOPIK目标。'},landing:{...en.landing,eyebrow:'今天开始轻松学TOPIK',before:'每天一道题，',strong:'一步步接近',after:'TOPIK目标',description:'从今日测验到TOPIK II 53题图表写作。\n一点点积累属于你的学习记录。',continue:'继续学习',start:'免费开始',free:'注册免费 · 无需银行卡',mission:'今日任务 +50 P',goal:'今日目标',goalText:'阅读3题',trust:'一个人学习也不再迷茫',trustItems:['今日测验','即时解析','写作记录','积分奖励'],kicker:'小而有效的学习习惯',title:'只保留TOPIK真正需要的内容',intro:'告别复杂计划，从每天能完成的任务开始。',features:[['3分钟今日测验','完成实战题并立即查看答案和解析。'],['53题图表写作','比较图表核心数据，练习200～300字答案。'],['看得见的成长','每次完成学习，积分和记录都会累积。']],ctaKicker:'今天就是最早的开始',ctaTitle:'准备好完成第一题了吗？',cta:'立即开始'},login:{...en.login,secure:'安全保存在你的设备',headline:'再次和Octo一起\n进步吧！',subtitle:'登录后继续今天的小任务。',home:'返回首页',title:'登录',intro:'还没有账号？使用任意邮箱即可开始。',email:'电子邮箱',password:'密码',passwordPlaceholder:'至少4个字符',submit:'登录并开始学习',demo:'体验说明',demoText:'输入内容只保存在此浏览器。',emailError:'请输入有效的电子邮箱。',passwordError:'请输入至少4个字符。'} }
const vi={...en,meta:{title:'Octopus TOPIK | Mỗi ngày một bước',description:'Luyện bài TOPIK và viết biểu đồ câu 53 mỗi ngày, tích điểm và lưu lại tiến bộ.'},layout:{home:'Trang chủ Octopus TOPIK',nav:'Menu chính',dashboard:'Bảng học tập',quiz:'Bài hôm nay',answers:'Bài viết câu 53',login:'Đăng nhập',start:'Bắt đầu miễn phí',logout:'Đăng xuất',language:'Chọn ngôn ngữ',menu:'Mở menu',footer:'Một bước nhỏ hôm nay đưa bạn gần hơn tới mục tiêu TOPIK.'},landing:{...en.landing,eyebrow:'Bắt đầu TOPIK thật nhẹ nhàng hôm nay',before:'Mỗi ngày một câu,',strong:'gần mục tiêu hơn',after:'từng bước',description:'Từ bài kiểm tra hôm nay đến viết biểu đồ TOPIK II câu 53.\nTích lũy hồ sơ học tập của riêng bạn từng ngày.',continue:'Tiếp tục học',start:'Bắt đầu miễn phí',free:'Đăng ký miễn phí · Không cần thẻ',mission:'Nhiệm vụ hôm nay +50 P',goal:'Mục tiêu hôm nay',goalText:'3 câu đọc hiểu',trust:'Không còn bối rối khi học một mình',trustItems:['Bài hôm nay','Giải thích ngay','Lưu bài viết','Thưởng điểm'],kicker:'Thói quen nhỏ nhưng hiệu quả',title:'Chỉ những gì bạn cần cho TOPIK',intro:'Bỏ kế hoạch phức tạp, bắt đầu với phần học có thể hoàn thành mỗi ngày.',features:[['Bài kiểm tra 3 phút','Làm câu hỏi sát đề và xem đáp án, giải thích ngay.'],['Viết biểu đồ câu 53','So sánh số liệu chính và luyện bài 200–300 ký tự.'],['Tiến bộ nhìn thấy được','Điểm và lịch sử được tích lũy sau mỗi bài học.']],ctaKicker:'Hôm nay là lúc sớm nhất để bắt đầu',ctaTitle:'Sẵn sàng làm câu đầu tiên?',cta:'Bắt đầu ngay'},login:{...en.login,secure:'Lưu an toàn trên thiết bị',headline:'Cùng Octo\ntiến bộ tiếp nhé?',subtitle:'Đăng nhập để tiếp tục nhiệm vụ nhỏ hôm nay.',home:'Về trang chủ',title:'Đăng nhập',intro:'Chưa có tài khoản? Dùng email bất kỳ để bắt đầu.',email:'Email',password:'Mật khẩu',passwordPlaceholder:'Ít nhất 4 ký tự',submit:'Đăng nhập và học',demo:'Thông tin trải nghiệm',demoText:'Dữ liệu chỉ được lưu trong trình duyệt này.',emailError:'Hãy nhập email hợp lệ.',passwordError:'Hãy nhập ít nhất 4 ký tự.'} }
const mn={...en,meta:{title:'Octopus TOPIK | Өдөр бүр нэг алхам',description:'Өдөр бүр TOPIK сорил, 53-р даалгаврын график бичвэрээр дадлага хийж ахицаа хадгалаарай.'},layout:{home:'Octopus TOPIK нүүр',nav:'Үндсэн цэс',dashboard:'Хяналтын самбар',quiz:'Өнөөдрийн сорил',answers:'53-р хариулт',login:'Нэвтрэх',start:'Үнэгүй эхлэх',logout:'Гарах',language:'Хэл сонгох',menu:'Цэс нээх',footer:'Өнөөдрийн жижиг алхам таныг TOPIK зорилгод ойртуулна.'},landing:{...en.landing,eyebrow:'TOPIK-оо өнөөдөр хөнгөн эхлүүлээрэй',before:'Өдөр бүр нэг асуулт,',strong:'зорилгодоо нэг алхам',after:'ойртоорой',description:'Өнөөдрийн сорилоос TOPIK II 53-р график бичвэр хүртэл.\nСуралцсан түүхээ бага багаар цуглуулаарай.',continue:'Үргэлжлүүлэн сурах',start:'Үнэгүй эхлэх',free:'Үнэгүй бүртгэл · Карт шаардлагагүй',mission:'Өнөөдрийн даалгавар +50 P',goal:'Өнөөдрийн зорилго',goalText:'Унших 3 асуулт',trust:'Ганцаараа сурахад ч ойлгомжтой',trustItems:['Өнөөдрийн сорил','Шууд тайлбар','Бичгийн түүх','Онооны шагнал'],kicker:'Жижиг боловч үр дүнтэй дадал',title:'TOPIK-д хэрэгтэй зүйлс л энд бий',intro:'Төвөгтэй төлөвлөгөөг орхиод өдөр бүр дуусгаж чадах хэмжээнээс эхлээрэй.',features:[['3 минутын сорил','Шалгалтын асуулт бодож хариу, тайлбарыг шууд харна.'],['53-р график бичвэр','Гол тоонуудыг харьцуулж 200–300 тэмдэгтээр бичнэ.'],['Харагдах ахиц','Хичээл дуусах бүрд оноо, түүх нэмэгдэнэ.']],ctaKicker:'Эхлэх хамгийн эрт өдөр бол өнөөдөр',ctaTitle:'Эхний асуултаа бодоход бэлэн үү?',cta:'Одоо эхлэх'},login:{...en.login,secure:'Төхөөрөмжид аюулгүй хадгална',headline:'Octo-той дахин\nхамтдаа ахицгаая!',subtitle:'Нэвтэрч өнөөдрийн жижиг даалгавраа үргэлжлүүлээрэй.',home:'Нүүр хуудас',title:'Нэвтрэх',intro:'Бүртгэлгүй юу? Дурын имэйлээр эхэлж болно.',email:'Имэйл',password:'Нууц үг',passwordPlaceholder:'Дор хаяж 4 тэмдэгт',submit:'Нэвтэрч сурах',demo:'Туршилтын мэдээлэл',demoText:'Мэдээлэл зөвхөн энэ хөтөчид хадгалагдана.',emailError:'Зөв имэйл оруулна уу.',passwordError:'Дор хаяж 4 тэмдэгт оруулна уу.'} }
const ja={...en,meta:{title:'Octopus TOPIK | 毎日一歩ずつ',description:'毎日のTOPIKクイズと53番グラフ作文で練習し、ポイントと学習記録を積み上げましょう。'},layout:{home:'Octopus TOPIKホーム',nav:'メインメニュー',dashboard:'ダッシュボード',quiz:'今日のクイズ',answers:'53番答案',login:'ログイン',start:'無料で始める',logout:'ログアウト',language:'言語を選択',menu:'メニューを開く',footer:'今日の小さな一歩がTOPIK合格に近づけます。'},landing:{...en.landing,eyebrow:'今日から気軽にTOPIK学習',before:'毎日一問、',strong:'合格に近づく',after:'習慣',description:'今日のクイズからTOPIK II 53番グラフ作文まで。\n自分だけの学習記録を少しずつ積み上げましょう。',continue:'学習を続ける',start:'無料で始める',free:'登録無料 · カード不要',mission:'今日のミッション +50 P',goal:'今日の目標',goalText:'読解クイズ3問',trust:'一人でも迷わない学習',trustItems:['今日のクイズ','すぐに解説','作文記録','ポイント報酬'],kicker:'小さくても確かな学習ルーティン',title:'TOPIK対策に必要なものだけ',intro:'複雑な計画ではなく、毎日完了できる量から始めましょう。',features:[['3分今日のクイズ','実戦形式の問題を解き、正解と解説をすぐ確認。'],['53番グラフ作文','重要な数値を比較し、200～300字の答案を練習。'],['見える成長','学習を終えるたびポイントと記録が積み上がります。']],ctaKicker:'今日がいちばん早いスタート',ctaTitle:'最初の一問を解く準備はできましたか？',cta:'今すぐ始める'},login:{...en.login,secure:'端末に安全に保存',headline:'Octoとまた\n成長しませんか？',subtitle:'ログインして今日の小さなミッションを続けましょう。',home:'ホームへ',title:'ログイン',intro:'アカウントがなくても、任意のメールですぐ始められます。',email:'メール',password:'パスワード',passwordPlaceholder:'4文字以上',submit:'ログインして学習',demo:'体験のご案内',demoText:'入力内容はこのブラウザにのみ保存されます。',emailError:'正しいメールアドレスを入力してください。',passwordError:'4文字以上入力してください。'} }

// Keep the writing navigation generic now that both Question 53 and 54 are available.
zh.layout.answers='写作练习'
vi.layout.answers='Luyện viết'
mn.layout.answers='Бичгийн дадлага'
ja.layout.answers='作文練習'

export const translations={ko,en,zh,vi,mn,ja}
