import { ArrowRight,CheckCircle2,ChevronRight,Clock3,Flame,PenLine,Play,Trophy } from 'lucide-react';import { Link,useNavigate } from 'react-router-dom';import Layout from '../components/Layout';import { Button,Card,ProgressBar } from '../components/ui';import { useApp } from '../context/AppContext';import { weeklyActivity } from '../data/mockData'
export default function DashboardPage(){const {user,points,completedQuizIds,answers}=useApp();const navigate=useNavigate();const writingAnswers=answers.filter(answer=>answer.promptNumber===53);const quizDone=completedQuizIds.includes('daily-quiz-v1');const today=new Intl.DateTimeFormat('ko-KR',{month:'long',day:'numeric',weekday:'long'}).format(new Date());const max=Math.max(...weeklyActivity.map(i=>i.value));return <Layout><main className="dashboard page-width">
 <div className="dashboard-greeting"><div><span>{today}</span><h1>{user.name}님, 오늘도 <em>한 걸음</em> 가볼까요?</h1><p>작은 학습이 쌓여 큰 실력이 됩니다.</p></div><div className="streak-badge"><Flame/><span><b>{completedQuizIds.length+writingAnswers.length}일</b> 학습 기록</span></div></div>
 <section className="stats-grid"><Card><span className="stat-label">보유 포인트</span><strong>{points.toLocaleString()} <small>P</small></strong><span className="stat-note purple"><Trophy size={14}/> 학습할수록 쌓여요</span></Card><Card><span className="stat-label">완료한 학습</span><strong>{completedQuizIds.length+writingAnswers.length} <small>개</small></strong><span className="stat-note"><CheckCircle2 size={14}/> 오늘도 기록해 보세요</span></Card><Card><span className="stat-label">작성한 53번 답안</span><strong>{writingAnswers.length} <small>개</small></strong><Link to="/answers">답안 모아보기 <ChevronRight size={14}/></Link></Card></section>
 <div className="dashboard-grid"><div className="dashboard-main"><div className="block-title"><div><span>TODAY'S MISSION</span><h2>오늘의 학습</h2></div><small>1일 권장 학습량</small></div>
 <Card className="mission-card featured"><div className="mission-icon"><Play fill="currentColor"/></div><div className="mission-body"><span className="tag">TOPIK II · 읽기</span><h3>오늘의 퀴즈 3문제</h3><p>실전 감각을 깨우는 짧고 알찬 문제예요.</p><div className="mission-meta"><span><Clock3 size={15}/> 약 3분</span><span>완료 시 최대 +50 P</span></div></div><Button variant={quizDone?'soft':'primary'} onClick={()=>navigate('/quiz/today')}>{quizDone?'다시 풀기':'퀴즈 시작'} <ArrowRight size={17}/></Button></Card>
 <Card className="mission-card"><div className="mission-icon coral"><PenLine/></div><div className="mission-body"><span className="tag coral-text">TOPIK II · 쓰기</span><h3>53번 그래프 답안 작성</h3><p>수치를 비교하고 변화의 특징을 정확하게 설명해요.</p><div className="mission-meta"><span><Clock3 size={15}/> 약 15분</span><span>완료 시 +30 P</span></div></div><Button variant="outline" onClick={()=>navigate('/answers/new')}>답안 쓰기 <ArrowRight size={17}/></Button></Card></div>
 <aside className="dashboard-side"><Card className="weekly-card"><div className="block-title"><div><span>WEEKLY</span><h2>이번 주 학습</h2></div><b>27문제</b></div><div className="bar-chart">{weeklyActivity.map(item=><div key={item.day} className="bar-item"><span className={item.value===max?'active':''} style={{height:`${Math.max(12,item.value/max*100)}%`}}/><small>{item.day}</small></div>)}</div><ProgressBar label="주간 목표" value={68}/></Card><Card className="tip-card"><span>💡 오늘의 학습 팁</span><p>문제를 틀렸다면 정답보다 <b>왜 틀렸는지</b> 한 문장으로 정리해 보세요.</p></Card></aside></div>
 </main></Layout>}
