import { ArrowRight,Award,BookOpenCheck,Check,PencilLine,Sparkles,Timer } from 'lucide-react'
import { useNavigate } from 'react-router-dom';import Layout from '../components/Layout';import { Button,Card } from '../components/ui';import { useApp } from '../context/AppContext'
export default function LandingPage(){const navigate=useNavigate();const {user}=useApp();const start=()=>navigate(user?'/dashboard':'/login');return <Layout><main>
 <section className="hero page-width"><div className="hero-copy"><div className="eyebrow"><Sparkles size={16}/> TOPIK 학습, 오늘부터 가볍게</div><h1>매일 한 문제,<br/><em>합격에 가까워지는</em> 습관</h1><p>오늘의 퀴즈부터 TOPIK II 53번 그래프 쓰기까지.<br/>나만의 학습 기록을 차곡차곡 쌓아 보세요.</p><div className="hero-actions"><Button size="lg" onClick={start}>{user?'학습 계속하기':'무료로 시작하기'} <ArrowRight size={18}/></Button><span><Check size={16}/> 가입 즉시 무료 · 카드 등록 없음</span></div></div>
 <div className="hero-visual brand-hero-visual" aria-label="옥토와 함께하는 TOPIK 성장 흐름"><div className="hero-glow"/><img className="hero-brand-illustration" src="/assets/hero-illustration.svg" alt="오늘의 미션을 완료하고 포인트를 모으는 옥토 캐릭터"/><div className="floating-pill"><Award size={18}/> 오늘의 미션 +50 P</div><div className="hero-mini-card"><span>오늘의 목표</span><strong>읽기 퀴즈 3문제</strong><div className="mini-progress"><span style={{width:'72%'}}/></div></div></div></section>
 <section className="trust-strip"><span>혼자여도 막막하지 않게</span><strong>오늘의 퀴즈</strong><i/><strong>즉시 해설</strong><i/><strong>쓰기 기록</strong><i/><strong>포인트 보상</strong></section>
 <section className="features page-width"><div className="section-heading"><span>작지만 확실한 학습 루틴</span><h2>TOPIK 준비에 필요한 것만 담았어요</h2><p>복잡한 계획 대신, 매일 완료할 수 있는 분량으로 시작하세요.</p></div><div className="feature-grid"><Card><div className="icon-box lilac"><Timer/></div><h3>3분 오늘의 퀴즈</h3><p>실전 유형 문제를 풀고 정답과 해설을 바로 확인해요.</p></Card><Card><div className="icon-box peach"><PencilLine/></div><h3>53번 그래프 쓰기</h3><p>그래프의 핵심 수치를 비교하며 200~300자 답안을 연습해요.</p></Card><Card><div className="icon-box mint"><BookOpenCheck/></div><h3>눈에 보이는 성장</h3><p>학습을 마칠 때마다 포인트와 기록이 차곡차곡 쌓여요.</p></Card></div></section>
 <section className="cta-band page-width"><div><span>오늘이 가장 빠른 시작이에요</span><h2>첫 문제를 풀 준비가 됐나요?</h2></div><Button variant="light" size="lg" onClick={start}>지금 시작하기 <ArrowRight size={18}/></Button></section>
 </main></Layout>}
