import { ArrowRight,Award,BookOpenCheck,Check,PencilLine,Sparkles,Timer } from 'lucide-react'
import { useNavigate } from 'react-router-dom';import Layout from '../components/Layout';import { Button,Card } from '../components/ui';import { useApp } from '../context/AppContext'
export default function LandingPage(){const navigate=useNavigate();const {user}=useApp();const start=()=>navigate(user?'/dashboard':'/login');return <Layout><main>
 <section className="hero page-width"><div className="hero-copy"><div className="eyebrow"><Sparkles size={16}/> TOPIK 학습, 오늘부터 가볍게</div><h1>매일 한 문제,<br/><em>합격에 가까워지는</em> 습관</h1><p>오늘의 퀴즈부터 TOPIK II 53번 그래프 쓰기까지.<br/>나만의 학습 기록을 차곡차곡 쌓아 보세요.</p><div className="hero-actions"><Button size="lg" onClick={start}>{user?'학습 계속하기':'무료로 시작하기'} <ArrowRight size={18}/></Button><span><Check size={16}/> 가입 즉시 무료 · 카드 등록 없음</span></div></div>
 <div className="hero-visual" aria-label="옥토퍼스 토픽 학습 현황 미리보기"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><Card className="preview-card"><div className="preview-top"><span className="mini-logo">O</span><span>오늘의 학습</span><strong>+50 P</strong></div><div className="streak"><span>🔥</span><div><b>7일 연속 학습 중!</b><small>이번 주 목표까지 2일 남았어요</small></div></div><div className="mini-progress"><span style={{width:'72%'}}/></div><div className="quiz-preview"><small>TOPIK II · 읽기</small><b>빈칸에 들어갈 알맞은 표현은?</b><span>정답을 선택해 주세요</span></div></Card><div className="floating-pill"><Award size={18}/> 이번 주 320 P</div></div></section>
 <section className="trust-strip"><span>혼자여도 막막하지 않게</span><strong>오늘의 퀴즈</strong><i/><strong>즉시 해설</strong><i/><strong>쓰기 기록</strong><i/><strong>포인트 보상</strong></section>
 <section className="features page-width"><div className="section-heading"><span>작지만 확실한 학습 루틴</span><h2>TOPIK 준비에 필요한 것만 담았어요</h2><p>복잡한 계획 대신, 매일 완료할 수 있는 분량으로 시작하세요.</p></div><div className="feature-grid"><Card><div className="icon-box lilac"><Timer/></div><h3>3분 오늘의 퀴즈</h3><p>실전 유형 문제를 풀고 정답과 해설을 바로 확인해요.</p></Card><Card><div className="icon-box peach"><PencilLine/></div><h3>53번 그래프 쓰기</h3><p>그래프의 핵심 수치를 비교하며 200~300자 답안을 연습해요.</p></Card><Card><div className="icon-box mint"><BookOpenCheck/></div><h3>눈에 보이는 성장</h3><p>학습을 마칠 때마다 포인트와 기록이 차곡차곡 쌓여요.</p></Card></div></section>
 <section className="cta-band page-width"><div><span>오늘이 가장 빠른 시작이에요</span><h2>첫 문제를 풀 준비가 됐나요?</h2></div><Button variant="light" size="lg" onClick={start}>지금 시작하기 <ArrowRight size={18}/></Button></section>
 </main></Layout>}
