import { ArrowLeft,CheckCircle2,Crown,Home,Lightbulb,ListChecks,LockKeyhole,Save,Sparkles } from 'lucide-react'
import { useEffect,useMemo,useRef,useState } from 'react'
import { useNavigate,useParams } from 'react-router-dom'
import Layout from '../components/Layout'
import { Button,Card,Textarea } from '../components/ui'
import { useApp } from '../context/AppContext'
import { useLanguage } from '../i18n/LanguageContext'
import { getDailyWritingPrompt } from '../lib/dailyContent'
import { getWritingFeedback } from '../lib/writingFeedback'

export default function WriteAnswerPage(){
 const navigate=useNavigate();const {questionNumber}=useParams();const {t,path}=useLanguage();const {saveAnswer}=useApp();const number=Number(questionNumber)===54?54:53
 const writingPrompt=useMemo(()=>getDailyWritingPrompt(number),[number]);const feedback=useMemo(()=>getWritingFeedback(writingPrompt),[writingPrompt]);const feedbackRef=useRef(null)
 const [content,setContent]=useState('');const [error,setError]=useState('');const [saving,setSaving]=useState(false);const [draftSaved,setDraftSaved]=useState(false);const [savedAnswer,setSavedAnswer]=useState(null)
 const draftKey=`octopus-topic-answer-${number}-draft-${writingPrompt.dailyId}`
 useEffect(()=>{const draft=localStorage.getItem(draftKey);if(draft)setContent(draft)},[draftKey])
 useEffect(()=>{if(!content||savedAnswer)return;const timer=setTimeout(()=>{localStorage.setItem(draftKey,content);setDraftSaved(true)},600);return()=>clearTimeout(timer)},[content,draftKey,savedAnswer])
 useEffect(()=>{if(savedAnswer)feedbackRef.current?.scrollIntoView({behavior:'smooth',block:'start'})},[savedAnswer])
 const submit=()=>{const trimmed=content.trim();const length=trimmed.length;if(length<writingPrompt.minCharacters||length>writingPrompt.maxCharacters){setError(t(number===54?'writing.lengthError54':'writing.lengthError'));return}setSaving(true);setTimeout(()=>{const answer=saveAnswer({title:writingPrompt.title,promptNumber:number,promptId:writingPrompt.id,promptDate:writingPrompt.dateKey,content:trimmed,characterCount:length,freeFeedback:feedback});localStorage.removeItem(draftKey);setSavedAnswer(answer);setSaving(false)},650)}
 return <Layout><main className="writing-page page-width"><button className="back-link standalone" onClick={()=>navigate(path('/writing'))}><ArrowLeft size={16}/> {t('writing.backToLab')}</button><div className="writing-header"><div><span>{t('common.writing')}</span><h1><b>{number}</b> {t(number===54?'writing.title54':'writing.title')}</h1><p>{t(number===54?'writing.subtitle54':'writing.subtitle')}</p></div><div className="autosave"><CheckCircle2 size={16}/> {draftSaved?t('writing.saved'):t('writing.autosave')}</div></div><div className="writing-grid">
 {number===53?<Card className="prompt-card"><span className="prompt-label">{t('writing.graph')}</span><h2>{writingPrompt.title}</h2><p>{writingPrompt.description}</p><div className="graph-legend">{writingPrompt.series.map(item=><span key={item.key}><i style={{background:item.color}}/>{item.label}</span>)}</div><div className="writing-chart" role="img" aria-label={`${writingPrompt.title}. ${writingPrompt.description}`}>{writingPrompt.chartData.map(group=><div className="writing-chart-group" key={group.label}><div className="writing-bars">{group.values.map(item=>{const seriesItem=writingPrompt.series.find(series=>series.key===item.series);return <div className="writing-bar-wrap" key={item.series}><b>{item.value}%</b><span className="writing-bar" style={{height:`${item.value}%`,background:seriesItem.color}}/></div>})}</div><strong>{group.label}</strong></div>)}</div><small className="chart-source">{writingPrompt.source}</small><ol>{writingPrompt.questions.map(q=><li key={q}>{q}</li>)}</ol><div className="writing-tip"><Lightbulb/><div><b>{t('writing.tip')}</b><p>{t('writing.tipText')}</p></div></div></Card>:<Card className="prompt-card essay-prompt"><span className="prompt-label">{t('writing.essay')}</span><h2>{writingPrompt.title}</h2><p className="essay-topic">{writingPrompt.topic}</p><p>{writingPrompt.description}</p><ol>{writingPrompt.questions.map(q=><li key={q}>{q}</li>)}</ol><small className="chart-source">{writingPrompt.source}</small><div className="writing-tip"><Lightbulb/><div><b>{t('writing.tip54')}</b><p>{t('writing.tipText54')}</p></div></div></Card>}
 <Card className="editor-card"><div className="editor-top"><div><span>{t('writing.my')}</span><small>{number===54?t('writing.recommended54'):t('writing.recommended')}</small></div><span className={content.length>=writingPrompt.minCharacters&&content.length<=writingPrompt.maxCharacters?'count valid':'count'}>{content.length}{t('common.characters')}</span></div><Textarea label={t('writing.content')} aria-label={`${number}${t(number===54?'writing.title54':'writing.title')}`} placeholder={t(number===54?'writing.placeholder54':'writing.placeholder')} value={content} disabled={Boolean(savedAnswer)} onChange={e=>{setContent(e.target.value);setError('');setDraftSaved(false)}} error={error}/><div className="editor-footer"><span>{writingPrompt.minCharacters}~{writingPrompt.maxCharacters}{t('common.characters')} · {t('writing.autoNote')}</span><Button size="lg" onClick={submit} loading={saving} disabled={Boolean(savedAnswer)}>{savedAnswer?<CheckCircle2 size={18}/>:<Save size={18}/>} {savedAnswer?t('writing.saveComplete'):t('writing.save')}</Button></div></Card></div>
 {savedAnswer?<section className="writing-feedback" ref={feedbackRef} aria-live="polite"><div className="feedback-heading"><span><Sparkles size={18}/>{number===54?'+50 P':'+30 P'} {t('writing.feedbackKickerText')}</span><h2>{t(number===54?'writing.feedbackTitle54':'writing.feedbackTitle')}</h2><p>{t(number===54?'writing.feedbackIntro54':'writing.feedbackIntro')}</p></div><div className="feedback-grid"><Card className="feedback-answer"><span>{t('writing.mySavedAnswer')}</span><article>{savedAnswer.content}</article></Card>{number===53?<Card className="feedback-answer model"><span>{t('writing.modelAnswer')}</span><article>{feedback.modelAnswer}</article></Card>:<Card className="feedback-answer model outline-card"><span>{t('writing.outline')}</span><ol>{feedback.outline.map(item=><li key={item}>{item}</li>)}</ol></Card>}</div><Card className="feedback-explanation"><div><Lightbulb/><h3>{t('writing.explanation')}</h3></div><ul>{feedback.points.map(point=><li key={point}>{point}</li>)}</ul></Card><Card className="premium-feedback-card"><div className="premium-icon"><Crown/></div><div><span>{t('premium.badge')}</span><h3>{t('premium.resultTitle')}</h3><p>{t('premium.resultText')}</p></div><Button variant="soft" disabled><LockKeyhole size={17}/>{t('premium.soon')}</Button></Card><div className="feedback-actions"><Button variant="outline" onClick={()=>navigate(path('/dashboard'))}><Home size={17}/>{t('result.dashboard')}</Button><Button onClick={()=>navigate(path('/answers'))}><ListChecks size={17}/>{t('writing.viewAnswers')}</Button></div></section>:null}</main></Layout>
}
